[[s2i-aspnet-example]]
= .NET Core Sample App for OpenShift

This repository contains an example project that can be built using the
https://github.com/redhat-developer/s2i-dotnetcore[s2i-dotnetcore] builder
image, which can be used to create reproducible Docker images from your .NET
Core project's source code. The resulting images can be run using
https://docker.com[Docker] or deployed to OpenShift.

For more information about using these images with OpenShift, please see
the official
https://docs.openshift.com/enterprise/latest/using_images/s2i_images/dot_net_core.html[OpenShift
Documentation].

= Building and Running 

The sample application can be built and run either within OpenShift or
standalone by combining the application using s2i tool and running with
existing image using Docker. The following sections describes these processes.

== OpenShift

The dotnet-example template at https://github.com/redhat-developer/s2i-dotnetcore instantiates the example application.
The https://github.com/redhat-developer/s2i-dotnetcore/blob/master/README.md[README.md] describes how to use the template.

# Standalone

To build a new .NET Core application using a previously existing s2i-dotnetcore
builder, `dotnet/dotnet-30-rhel7`, execute the following command:

[source]
----
s2i build --ref=dotnetcore-3.0 --context-dir=app https://github.com/redhat-developer/s2i-dotnetcore-ex dotnet/dotnet-30-rhel7 aspnet-app
----

The resulting image can be executed using docker:

[source]
----
docker run -d -p 8080:8080 aspnet-app
----

Once the container is running, it should be accessible using:

[source]
----
curl http://127.0.0.1:8080
----

[[contributing]]
Contributing
~~~~~~~~~~~~

Contributions to this project (in the form of bug reports, patches, or pull
requests) are gratefully accepted by the maintainer.  Please see the
link:Contributing.adoc[Contributing.adoc] file contained in this package
for details.

[[copyright-license]]
Copyright and License
~~~~~~~~~~~~~~~~~~~~~

Copyright 2016-2017 by Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this package except in compliance with the License (see the `LICENSE` file
included in this distribution). You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
