= .NET Core Sample App for OpenShift Pipelines

This repository contains a simple MVC .NET Core application that can be deployed on OpenShift.

This branch contains code to make it easy to build and test the application
using OpenShift Pipelines. Please use the other branches for general OpenShift
use, including through tools like `oc` and `odo`.
 
= Deploying the application

An upcoming blog post will cover how to use this repository in detail.

== Copyright and License

Copyright 2016-2020 by Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not
use this package except in compliance with the License (see the `LICENSE` file
included in this distribution). You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.
